# Generated by Django 5.1.6 on 2025-03-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'movie_id')},
        ),
    ]
