# Generated by Django 5.1.6 on 2025-03-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=255)),
                ('tmdb_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_link',
            },
        ),
    ]
