# Generated by Django 5.1.6 on 2025-03-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AlterField(
            model_name='link',
            name='movie_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
