# Generated by Django 5.1.6 on 2025-03-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_link_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='tb_profile',
        ),
    ]
